### ISSUE TITLE
doesn't compile with lunatic 0.13.1

### ISSUE THREAD

**Issue by srl295** [lunatic-solutions/chat#11]
noting #10 …

> latest update on 2023-08-03, rust version 1.71.1 (eb26296b5 2023-08-03)

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/client.rs:64:68
    |
64  |         let coordinator = ProcessRef::<CoordinatorProcess>::lookup("coordinator").unwrap();
    |                           ---------------------------------------- ^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |                           |
    |                           required by a bound introduced by this call
    |
    = help: the trait `Sized` is not implemented for `str`
note: required by a bound in `ProcessRef::<T>::lookup`
   --> /Users/srl295/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lunatic-0.13.1/src/ap/mod.rs:395:19
    |
395 |     pub fn lookup<N: ProcessName>(name: &N) -> Option<Self> {
    |                   ^ required by this bound in `ProcessRef::<T>::lookup`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `telnet-chat` (bin "telnet-chat") due to previous error
```

**Comment by bkolobara** [comment]
Thanks for opening the issue. I updated all the dependencies, including lunatic to 0.14.1, and fixed a few small issues. It should compile again.

**Comment by srl295** [comment]
@bkolobara i can confirm it works, thanks! (was able to run the server and try it out now) I've gone on to something else but I might come back to this, it looks promising
